# Generated by Django 4.1.7 on 2023-05-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language_movie_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=2000, help_text='Enter the year movie was released'),
            preserve_default=False,
        ),
    ]
